### ISSUE TITLE
Tracking small issues in Sketch library

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#424]
@ajacobs21e (you can add them to a description)

**Comment by ajacobs21e** [comment]
form with icon - overrides

**Comment by doruskova** [comment]
- [x] Allowed to change text style for breadcrumbs (it's because of drill down menu that uses 16px breadcrumbs and don't want to duplicate symbols)
- [x] Fixed background style for drill down menu (hover). It was using disabled layer even if it's not disabled state.

**Comment by doruskova** [comment]
@ajacobs21e Yes, definitely! It's confusing now. But, there are two greys. So, I would like to know (use a plugin) how many components are using which layer.

**Comment by doruskova** [comment]
- [ ] Remove additional layer for dynamic color (it also needs more investigation because I don't know what's gonna happen)

- [ ] Change icons to one color (probably to black).

@ajacobs21e do you agree?

**Comment by doruskova** [comment]
- [x] Fixed wrong bg to white above the table (tables page) > the layer was overridden with a different color.

**Comment by doruskova** [comment]
- [x] Removed unused borders/fills from layers

**Comment by doruskova** [comment]
- [x] Fixed focus state
