### ISSUE TITLE
AAP Components review 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#563]
Review of components from Ansible team. 

@mcarrano Please let me know what you think :)) 

**Components that can be generalized in Sketch or added as a full component:** 

- [x] Delete modal - we can add the skeleton with a header, close button, and buttons.
- [x] Error - we can add it as an empty state and would be useful to have some specific examples in a template file. 
- [x] Empty state - add an empty state with the primary button and without it. We don't have any empty states in the library. Just a template file. 
- [x] Wizard - use just a skeleton for a wizard (header, left panel, background, buttons) and steps need to be added separately because it's difficult to add/remove them. 

When it comes to a structure in a library > I think it's feasible to do it without large changes in structure. 
For example, the delete modal will be added between existing modals. Other modals should have resizable buttons that can be removed. This change shouldn't mess up the library structure. 

**Components that can't be a part of larger components:**
Cards - too specific for Ansible
Details page - too specific for Ansible. 
Filters - are too specific for each app and resizing can be difficult

- [x] Framework - nav, and masthead are part of a template file. The header with breadcrumbs doesn't have to be a component. It would make sense to create a full component just with breadcrumbs so that you don't have to build them from scratch. 

Labels - already in a library and it's impossible to have specific labels in a library
List view- specific for Ansible
Tables - already in a library as full rows
Topology - too specific for the Ansible team 

https://docs.google.com/document/d/1iZ41RjzLHsw2y90wBy0WBksiILTwLKNwfNQqeNcOLXk/edit?usp=sharing

**Comment by mcarrano** [comment]
@doruskova I think this makes sense. I think that there may be some value to giving greater visibility to the Ansible library if some of the patterns are useful to developers on other projects short of adding them directly to the PatternFly library. One thing we can do is to publish a link directly to the Anisble design library here: https://www.patternfly.org/v4/community as a community project while adding a limited set of these components to the PattenFly symbol library as outlined above. Thoughts?

**Comment by doruskova** [comment]
@mcarrano All components should be updated :))

**Comment by doruskova** [comment]
@mcarrano I reached out to Ansible team and they think it's a great idea to publish a link directly to the Ansible design library :))
