### ISSUE TITLE
Extensions: React component groups

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#697]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/720
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/721
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/722
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/723
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/724
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/725
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/726
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/727
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/728
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/729
- [x] Penta: Ansible
```
