### ISSUE TITLE
Charts: Add skeleton variants for empty charts

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#733]
## Goal
Follow up to [Design issue](https://github.com/patternfly/patternfly-design/issues/1278) and [React issue](https://github.com/patternfly/patternfly-react/pull/10311)

```[tasklist]
### Tasks
- [ ] Define color tokens for skeleton charts
- [ ] Add a variant to each chart type in Figma
- [ ] Create tokens and core issues to implement change in v6
```

<img width="611" alt="Screenshot 2024-05-01 at 10 57 53 AM" src="https://github.com/patternfly/patternfly-design-kit/assets/28658548/a8434404-e800-490d-b011-4657dee612d9">

<img width="833" alt="Screenshot 2024-05-01 at 10 58 26 AM" src="https://github.com/patternfly/patternfly-design-kit/assets/28658548/6e1d22ad-34f5-4fac-a0c8-932188112cfc">

**Comment by phcox** [comment]
Not needed in the shift to vibe coding practices.
